apiVersion: apps/v1
kind: Deployment
metadata:
  name: button-shop-app
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: button-shop-app
  template:
    metadata:
      labels:
        app: button-shop-app
    spec:
      containers:
      - name: button-shop-app
        image: ghcr.io/mojski/buttonshop:832219d
        ports:
        - containerPort: 5080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: button-shop-svc
  namespace: button-shop
spec:
  ports:
  - port: 5080
    targetPort: 5080
  selector:
    app: button-shop-app