apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: button-shop
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
---
# grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: button-shop
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
---
# elasticsearch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.8.0
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: button-shop
spec:
  ports:
  - port: 9200
    targetPort: 9200
  - port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
---
# otel-collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        ports:
        - containerPort: 1888
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 13133
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 55679
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-svc
  namespace: button-shop
spec:
  ports:
  - port: 1888
    targetPort: 1888
  - port: 8888
    targetPort: 8888
  - port: 8889
    targetPort: 8889
  - port: 13133
    targetPort: 13133
  - port: 4317
    targetPort: 4317
  - port: 4318
    targetPort: 4318
  - port: 55679
    targetPort: 55679
  selector:
    app: otel-collector
---
# loki
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        ports:
        - containerPort: 3100
        - containerPort: 9095
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  namespace: button-shop
spec:
  ports:
  - port: 3100
    targetPort: 3100
  - port: 9095
    targetPort: 9095
  selector:
    app: loki
---
# tempo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: button-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        ports:
        - containerPort: 3200
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 9411
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-svc
  namespace: button-shop
spec:
  ports:
  - port: 3200
    targetPort: 3200
  - port: 4317
    targetPort: 4319
  - port: 4318
    targetPort: 4320
  - port: 9411
    targetPort: 9411
  selector:
    app: tempo