{
 "title": "Button Shop Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orders locations",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Button Colors",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_sold_red", "legendFormat": "__auto" },
    { "expr": "button_shop_sold_green", "legendFormat": "__auto" },
    { "expr": "button_shop_sold_blue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "waiting orders",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(button_shop_orders_waiting/button_shop_orders_total)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_orders_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_orders_shipped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "button_shop_orders_total", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_waiting", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_shipped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "_index:button_order_events",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}