{
 "title": "Technical dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_num_threads,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health/system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health/elasticsearch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health/otel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health/persistence\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"http://[^:]+:5080/health/redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs and Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "filters": [
        { "id": "6a5d2307", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "ButtonShop" ],
         "valueType": "string"
        },
        {
         "id": "status",
         "operator": "=",
         "scope": "intrinsic",
         "tag": "status",
         "valueType": "keyword"
        }
       ],
       "limit": 20,
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "{service_name=\"ButtonShop\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "ASP .NET Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "threads",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 5, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_num_threads{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exceptions per second",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(system_runtime_exception_count_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "handles",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_handles{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Managed memory used by heap ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_runtime_gen_0_size{instance=\"$instance\"}",
       "legendFormat": "Gen 0"
      },
      {
       "expr": "system_runtime_gen_1_size{instance=\"$instance\"}",
       "legendFormat": "Gen 1"
      },
      {
       "expr": "system_runtime_gen_2_size{instance=\"$instance\"}",
       "legendFormat": "Gen 2"
      },
      {
       "expr": "system_runtime_loh_size{instance=\"$instance\"}",
       "legendFormat": "LOH"
      },
      {
       "expr": "system_runtime_poh_size{instance=\"$instance\"}",
       "legendFormat": "POH"
      }
     ]
    },
    {
     "title": "Memory used by process",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "system_runtime_gc_heap_size{instance=\"$instance\"} * 1024 * 1024",
       "legendFormat": "Managed memory - used"
      },
      {
       "expr": "system_runtime_gc_committed{instance=\"$instance\"} * 1024 * 1024",
       "legendFormat": "Managed memory - committed"
      },
      {
       "expr": "process_working_set_bytes{instance=\"$instance\"}",
       "legendFormat": "Process working set"
      }
     ]
    },
    {
     "title": "GC collection count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "increase(dotnet_collection_count_total[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total known allocated memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes /1024/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "targets": [
      { "expr": "process_num_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Number of open handles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "targets": [
      { "expr": "process_open_handles", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Process working set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "process_working_set_bytes /1024/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(system_net_sockets_bytes_received{instance=\"$instance\"}[$__rate_interval]) * 8",
       "legendFormat": "receive rate"
      },
      {},
      {
       "expr": "rate(system_net_sockets_bytes_sent{instance=\"$instance\"}[$__rate_interval]) * 8",
       "legendFormat": "transmit rate"
      },
      {}
     ]
    }
   ]
  }
 ]
}