global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'buttonstats'
    static_configs:
      - targets: ['host.docker.internal:5080'] # scraps outside docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8081']