{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Orders locations",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Button Colors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_sold_red", "legendFormat": "__auto" },
    { "expr": "button_shop_sold_green", "legendFormat": "__auto" },
    { "expr": "button_shop_osold_blue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "button_shop_orders_total", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_waiting", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_shipped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total/waiting/shippe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "button_shop_orders_total", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_waiting", "legendFormat": "__auto" },
    { "expr": "button_shop_orders_shipped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "waiting orders",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(button_shop_orders_waiting/button_shop_orders_total)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } }
 ]
}