name: .NET 8 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: List files (debugging step)
        run: ls -la src

      - name: Restore dependencies
        run: dotnet restore src/ButtonShop.sln

      - name: Build the project
        run: dotnet build src/ButtonShop.sln --configuration Release --no-restore
